/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.50
 * Generated at: 2014-04-06 19:39:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import venture.Activity;
import venture.Movie;
import venture.MinuteTime;
import org.json.*;
import venture.JSONUtil;

public final class suggestions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=US-ASCII");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, maximum-scale=2.0, user-scalable=no\", target-densitydpi=device-dpi />\n");
      out.write("    <link href='http://fonts.googleapis.com/css?family=Codystar|Lobster|Londrina+Outline|Lato|Merriweather' rel='stylesheet' type='text/css'>\n");
      out.write("\t<link href=\"public/icons/css/fontello.css\" rel='stylesheet' type=\"text/css\">\n");
      out.write("\t<link rel=\"stylesheet\" href=\"//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css\">\n");
      out.write("    <script src=\"http://code.jquery.com/jquery-1.11.0.min.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"public/style.css\" />\n");
      out.write("    <title>Venture</title>\n");
      out.write("    \n");
      out.write("\t");

		Activity activity = (Activity)request.getAttribute("activity");	
		request.setAttribute("activity", activity);
		double lat = Double.parseDouble((String)request.getAttribute("latitude"));
		double lng = Double.parseDouble((String)request.getAttribute("longitude"));
		
		String modeOfTransit = (String)request.getAttribute("modeOfTransit");
		
		if (modeOfTransit == null) {
			modeOfTransit = "driving";
		}
		String imageSrc = "http://maps.googleapis.com/maps/api/streetview?size=600x300&location=" + activity.latitude + "," + activity.longitude + "&heading=151.78&pitch=-0.76&sensor=false";
	
		StringBuilder addressURL = new StringBuilder();
		for (int i = 0; i < activity.address.length(); i++) {
			if (activity.address.charAt(i) ==' ') {
				addressURL.append("+");
			} else {
				addressURL.append(activity.address.charAt(i));
			}
		}
	
      out.write("\n");
      out.write("    \n");
      out.write("    <script type=\"text/javascript\">\n");
      out.write("        var loginBar;\n");
      out.write("\n");
      out.write("        function toggleLoginBar() {\n");
      out.write("           loginBar.slideToggle(); \n");
      out.write("        }\n");
      out.write("        \n");
      out.write("        var selectedId = \"");
      out.print(request.getAttribute("modeOfTransit") );
      out.write("\";\n");
      out.write("        var isParks = ");
      out.print(request.getAttribute("isParks").equals("YES"));
      out.write(";\n");
      out.write("        var isBars = ");
      out.print(request.getAttribute("isBars").equals("YES"));
      out.write(";\n");
      out.write("        var isFood = ");
      out.print(request.getAttribute("isFood").equals("YES"));
      out.write(";\n");
      out.write("        var isMovies = ");
      out.print(request.getAttribute("isMovies").equals("YES"));
      out.write(";\n");
      out.write("        var isShopping = ");
      out.print(request.getAttribute("isShopping").equals("YES"));
      out.write(";\n");
      out.write("        var isOther = ");
      out.print(request.getAttribute("isOther").equals("YES"));
      out.write(";\n");
      out.write("        \n");
      out.write("        // radio for modes of transportation\n");
      out.write("        $(document).ready(function() {\n");
      out.write("            $('.tg').on('click',function() {\n");
      out.write("                $('#transpo-group > .tg > i').removeClass('selected').addClass('unselected');\n");
      out.write("                $(this).children('i').toggleClass('unselected selected');\n");
      out.write("                selectedId = $(this).children('i').attr('id');\n");
      out.write("                \n");
      out.write("                document.getElementById('map-frame').src = \"https://www.google.com/maps/embed/v1/directions?key=AIzaSyCwehTkiWGttVWmKbBYm-V0Lj1UvWCyzXg\"\n");
      out.write("\t\t\t\t  +\"&origin=");
      out.print(request.getAttribute("latitude"));
      out.write(',');
      out.print(request.getAttribute("longitude"));
      out.write("\"\n");
      out.write("\t\t\t\t  +\"&destination=");
      out.print(addressURL.toString());
      out.write("\"\n");
      out.write("\t\t\t\t  +\"&mode=\"+selectedId;\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        // Toggle for categories\n");
      out.write("        $(document).ready(function() {\n");
      out.write("            $('.cat-i').on('click',function() {\n");
      out.write("                $(this).children('i').toggleClass('unselected selected');\n");
      out.write("                var selected = $(this).children('i').hasClass('selected');\n");
      out.write("                var selectedCategory = $(this).children('i').attr('id');\n");
      out.write("                console.log(selectedCategory);\n");
      out.write("                if (selectedCategory === \"parks\") {\n");
      out.write("                \tisParks = selected;\n");
      out.write("                }\n");
      out.write("\t\t\t\tif (selectedCategory === \"bars\") {\n");
      out.write("                \tisBars = selected;\n");
      out.write("                } \n");
      out.write("\t\t\t\tif (selectedCategory === \"food\") {\n");
      out.write("                \tisFood = selected;\n");
      out.write("                } \n");
      out.write("\t\t\t\tif (selectedCategory === \"movies\") {\n");
      out.write("                \tisMovies = selected;\n");
      out.write("                }\n");
      out.write("\t\t\t\tif (selectedCategory === \"shopping\") {\n");
      out.write("                \tisShopping = selected;\n");
      out.write("                } \n");
      out.write("\t\t\t\tif (selectedCategory === \"other\") {\n");
      out.write("                \tisOther = selected;\n");
      out.write("                } \n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    </script>\n");
      out.write("    \n");
      out.write("    <script>\n");
      out.write("    \tvar suggestionForm;\n");
      out.write("    \tvar acceptanceForm;\n");
      out.write("    \t\n");
      out.write("    \tfunction rejectSuggestion() {\n");
      out.write("    \t\tdocument.getElementById('transport').value = selectedId;\n");
      out.write("    \t\tdocument.getElementById('parksInput').value = isParks ? \"YES\" : \"NO\";\n");
      out.write("    \t\tdocument.getElementById('barsInput').value = isBars ? \"YES\" : \"NO\";\n");
      out.write("    \t\tdocument.getElementById('foodInput').value = isFood ? \"YES\" : \"NO\";\n");
      out.write("    \t\tdocument.getElementById('moviesInput').value = isMovies ? \"YES\" : \"NO\";\n");
      out.write("    \t\tdocument.getElementById('shoppingInput').value = isShopping ? \"YES\" : \"NO\";\n");
      out.write("    \t\tdocument.getElementById('otherInput').value = isOther ? \"YES\" : \"NO\";\n");
      out.write("    \t\tsuggestionForm.submit();\n");
      out.write("    \t}\n");
      out.write("    \t\n");
      out.write("    \tfunction acceptSuggestion() {\n");
      out.write("    \t\tdocument.getElementById('accept-transport').value = selectedId;\n");
      out.write("    \t\tacceptanceForm.submit();\n");
      out.write("    \t}\n");
      out.write("    \t\n");
      out.write("\t    window.onload = function() {\n");
      out.write("\t    \tloginBar = $(\"#login-bar\");\n");
      out.write("\t\t\tsuggestionForm = document.getElementById(\"suggestion\");\n");
      out.write("\t\t\tacceptanceForm = document.getElementById(\"accept\");\n");
      out.write("\t\t}\n");
      out.write("    \n");
      out.write("    </script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<div id=\"content-wrapper\">\n");
      out.write("        <div id=\"header\">\n");
      out.write("            <a href=\"index.html\"><span id=\"hdr\">Venture</span></a>\n");
      out.write("            <div onclick=\"toggleLoginBar();\" id=\"login-icon\">\n");
      out.write("                <div style=\"position: relative;\" class=\"dropdown\">\n");
      out.write("                    <span id=\"hdr\"><i class=\"icon-cog\"></i></span>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("                \n");
      out.write("       \t<div id=\"login-bar\">\n");
      out.write("            <span id=\"icon-bar\">\n");
      out.write("                <span id=\"category-group\">\n");
      out.write("                \n");
      out.write("                    <span class=\"cat-i\"><i class=\"icon-tree-1 ");
      out.print( ((String)request.getAttribute("isParks")).equals("YES") ? "selected" : "unselected" );
      out.write("\" title=\"Parks\" id=\"parks\"></i> </span>\n");
      out.write("                    <span class=\"cat-i\"><i class=\"icon-bar ");
      out.print( ((String)request.getAttribute("isBars")).equals("YES") ? "selected" : "unselected" );
      out.write("\" title=\"Bars\" id=\"bars\"></i> </span>\n");
      out.write("                    <span class=\"cat-i\"><i class=\"icon-restaurant ");
      out.print( ((String)request.getAttribute("isFood")).equals("YES") ? "selected" : "unselected" );
      out.write("\" title=\"Food\" id=\"food\"></i> </span>\n");
      out.write("                    <span class=\"cat-i\"><i class=\"icon-cinema ");
      out.print( ((String)request.getAttribute("isMovies")).equals("YES") ? "selected" : "unselected" );
      out.write("\" title=\"Movies\" id=\"movies\"></i> </span>\n");
      out.write("                    <span class=\"cat-i\"><i class=\"icon-shop ");
      out.print( ((String)request.getAttribute("isShopping")).equals("YES") ? "selected" : "unselected" );
      out.write("\" title=\"Shopping\" id=\"shopping\"></i> </span>\n");
      out.write("                    <span class=\"cat-i\"><i class=\"icon-embassy ");
      out.print( ((String)request.getAttribute("isOther")).equals("YES") ? "selected" : "unselected" );
      out.write("\" title=\"Other\" id=\"other\"></i></span>\n");
      out.write("                </span>\n");
      out.write("                <span id=\"transpo-group\">\n");
      out.write("                    <span class=\"tg\"><i class=\"icon-bicycle ");
      out.print( ((String)request.getAttribute("modeOfTransit")).equals("bicycling") ? "selected" : "unselected" );
      out.write("\" title=\"Bike\" id=\"bicycling\"></i> </span>\n");
      out.write("                    <span class=\"tg\"><i class=\"icon-bus ");
      out.print( ((String)request.getAttribute("modeOfTransit")).equals("transit") ? "selected" : "unselected" );
      out.write("\" title=\"Public Transit\" id=\"transit\"></i> </span>\n");
      out.write("                    <span class=\"tg\"><i class=\"icon-fuel ");
      out.print( ((String)request.getAttribute("modeOfTransit")).equals("driving") ? "selected" : "unselected" );
      out.write("\" title=\"Drive\" id=\"driving\"></i> </span>\n");
      out.write("                    <span class=\"tg\"><i class=\"icon-pitch ");
      out.print( ((String)request.getAttribute("modeOfTransit")).equals("walking") ? "selected" : "unselected" );
      out.write("\" title=\"Walk\" id=\"walking\"></i></span>\n");
      out.write("                </span>\n");
      out.write("            </span>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        <div id=\"content\" style=\"width: 100%; position: relative;\">\n");
      out.write("            <div id=\"event-photo-container\">\n");
      out.write("                <div id=\"event-photo-wrapper\">\n");
      out.write("                    <img src=");
      out.print(imageSrc);
      out.write(" />\n");
      out.write("                </div>\n");
      out.write("                <table id=\"vote-under\" style=\"position: absolute; width: 100%; bottom: -30px;\">\n");
      out.write("                    <tr>\n");
      out.write("                        <td><div class=\"circular-button\" style=\"align:left\" onclick=\"rejectSuggestion()\"></div></td>\n");
      out.write("                        <td><div class=\"circular-button\" style=\"align:right\" onclick=\"acceptSuggestion()\"></div></td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("                <table id=\"vote-wrapper\" style=\"pointer-events: none; bottom: 45px;\">\n");
      out.write("                    <tr>\n");
      out.write("                        <td><!--span id=\"vote-words-row\">Meh...</span><br /--><i class=\"icon-cancel\"></i></td>\n");
      out.write("                        <td><!--span id=\"vote-words-row\">Let's go!</span><br /--><i class=\"icon-ok\"></i></td>\n");
      out.write("                    </tr>\n");
      out.write("                </table>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("            ");

            	//String url = "http://maps.googleapis.com/maps/api/distancematrix/json?origins=" + lat +"," + lng + "&destinations=" + addressURL + "&mode=" + modeOfTransit + "&sensor=false&key=AIzaSyCwehTkiWGttVWmKbBYm-V0Lj1UvWCyzXg";	
            	String url = "http://maps.googleapis.com/maps/api/distancematrix/json?origins=" + lat + "," + lng + "&destinations=" + addressURL + "%20%20%20%20%20%20%20%20%20%20%20%20&mode=" + modeOfTransit + "&sensor=false&%20%20%20%20%20%20%20%20%20%20%20%20key=AIzaSyCwehTkiWGttVWmKbBYm-V0Lj1UvWCyzXg";
            	System.out.println(url);
            	JSONObject jsonObj = JSONUtil.readJsonFromUrl(url);
            	System.out.println(jsonObj);
            	String distance = null;
            	String duration = null;
            	try {
            		distance = jsonObj.getJSONArray("rows").getJSONObject(0).getJSONArray("elements").getJSONObject(0).getJSONObject("distance").getString("text");
            		duration = jsonObj.getJSONArray("rows").getJSONObject(0).getJSONArray("elements").getJSONObject(0).getJSONObject("duration").getString("text");
            		System.out.println(distance);
            		System.out.println(duration);
            	}
            	catch (JSONException e) {
            		e.printStackTrace();
            	}
            	
            
      out.write("\n");
      out.write("            \n");
      out.write("            <div id=\"event-info\">\n");
      out.write("\t            <div id=\"event-title-container\"><span id=\"event-title\">");
      out.print(activity.title);
      out.write("</span></div>\n");
      out.write("\t            <div id=\"event-details-container\">\n");
      out.write("\t                <span id=\"event-dist\">\n");
      out.write("\t                \t");

	                		if ((duration != null) && (distance != null)) {
      out.write("\n");
      out.write("\t                \t\t\t");
      out.print(duration);
      out.write(' ');
      out.write('|');
      out.write(' ');
      out.print( distance);
      out.write(" away\n");
      out.write("\t                \t\t");
}
	                	
      out.write("\n");
      out.write("\t                </span><br />\n");
      out.write("\t               \t<span id=\"event-details\">\n");
      out.write("\t             \t\t");
 
	             			if (activity.website != null) {
	             				
      out.write("<a href=\"");
      out.print(activity.website);
      out.write('"');
      out.write('>');
      out.print(activity.website);
      out.write("</a><br>\n");
      out.write("\t             \t\t\t");
}
	             		
      out.write("\n");
      out.write("\t             \t\t");
 
	             			if (activity.phoneNumber != null) {
	             				
      out.write("| <a href=\"tel:+1");
      out.print(activity.phoneNumber);
      out.write('"');
      out.write('>');
      out.print(activity.phoneNumber);
      out.write("</a><br>\n");
      out.write("\t             \t\t\t");
}
	             		
      out.write("\n");
      out.write("\t             \t</span>\n");
      out.write("\t                <span id=\"event-addr\">");
      out.print(activity.address);
      out.write("</span>\n");
      out.write("\t            </div>\n");
      out.write("\t        </div> \n");
      out.write("\t        \n");
      out.write("\t        ");
 if (activity instanceof Movie && ((Movie)activity).trailer.length() > 0) { 
      out.write("\n");
      out.write("\t        <h1>");
      out.print( ((Movie)activity).starttime.toString() );
      out.write("</h1>\n");
      out.write("\t        <h3>");
      out.print((new MinuteTime()).toString() );
      out.write(" - Leave in ");
      out.print( ((Movie)activity).starttime.minute - (new MinuteTime()).minute );
      out.write(" minutes</h3>\n");
      out.write("\t        <div class=\"video-container\">\n");
      out.write("\t        \t<iframe width=\"560\" height=\"315\" src=\"");
      out.print(((Movie)activity).trailer);
      out.write("\" frameborder=\"0\" allowfullscreen></iframe>\n");
      out.write("\t        </div>\n");
      out.write("\t        ");
 } 
      out.write("\n");
      out.write("            \n");
      out.write("            <div id=\"map-container\">\n");
      out.write("                <iframe\n");
      out.write("                  id=\"map-frame\"\n");
      out.write("\t\t\t\t  width=\"600\"\n");
      out.write("\t\t\t\t  height=\"450\"\n");
      out.write("\t\t\t\t  frameborder=\"0\" style=\"border:0\"\n");
      out.write("\t\t\t\t  src=\"https://www.google.com/maps/embed/v1/directions?key=AIzaSyCwehTkiWGttVWmKbBYm-V0Lj1UvWCyzXg\n");
      out.write("\t\t\t\t  &origin=");
      out.print(request.getAttribute("latitude"));
      out.write(',');
      out.print(request.getAttribute("longitude"));
      out.write("\n");
      out.write("\t\t\t\t  &destination=");
      out.print(addressURL.toString());
      out.write("\n");
      out.write("\t\t\t\t  &mode=");
      out.print(modeOfTransit);
      out.write("\" >\n");
      out.write("\t\t\t\t</iframe>\n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("        <div id=\"footer\">\n");
      out.write("        \t");

        	if (session.getAttribute("user") != null) {
      out.write("\n");
      out.write("        \t\t<form name=\"logout\" action=\"LogoutServlet\" method=\"post\">\n");
      out.write("\t           \t\t<button class=\"btn btn-large btn-primary\" type=\"submit\"> \n");
      out.write("\t\t\t\t\t\tLog Out\n");
      out.write("\t           \t\t</button>\n");
      out.write("\t           \t\t&nbsp; &nbsp; &nbsp; &nbsp; &copy; Keenon, Jan, Amy, and Alanna\n");
      out.write("\t           \t</form>\n");
      out.write("        \t");
 } else {
      out.write("\n");
      out.write("\t           \t\t<a href=\"login.html\"><button class=\"btn btn-large btn-primary\" type=\"submit\"> \n");
      out.write("\t\t\t\t\t\tLog In\n");
      out.write("\t           \t\t</button></a>\n");
      out.write("\t           \t\t&nbsp; &nbsp; &nbsp; &nbsp; &copy; Keenon, Jan, Amy, and Alanna\n");
      out.write("        \t");
}
      out.write("\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("        <form style=\"display:none\" name=\"Suggestion\" id=\"suggestion\" action=\"GenerateSuggestionsServlet\" method=\"post\">\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"latitude\" name=\"latitude\" value=\"");
      out.print(request.getAttribute("latitude"));
      out.write("\">\t\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"longitude\" name=\"longitude\" value=\"");
      out.print(request.getAttribute("longitude"));
      out.write("\">\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"rejectedid\" name=\"rejectedid\" value=\"");
      out.print(((Activity)request.getAttribute("activity")).id);
      out.write("\">\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"transport\" id=\"transport\" value=\"drive\"><br>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"parks\" id=\"parksInput\" value=\"NO\"><br>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"bars\" id=\"barsInput\" value=\"NO\"><br>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"food\" id=\"foodInput\" value=\"NO\"><br>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"movies\" id=\"moviesInput\" value=\"NO\"><br>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"shopping\" id=\"shoppingInput\" value=\"NO\"><br>\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"other\" id=\"otherInput\" value=\"NO\"><br>\t\n");
      out.write("\t\t</form>\n");
      out.write("\t\t<form style=\"display:none\" name=\"Accept\" id=\"accept\" action=\"VentureOnServlet\" method=\"post\">\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"latitude\" name=\"latitude\" value=\"");
      out.print(request.getAttribute("latitude"));
      out.write("\">\t\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"longitude\" name=\"longitude\" value=\"");
      out.print(request.getAttribute("longitude"));
      out.write("\">\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"address\" name=\"address\" value=\"");
      out.print(((Activity)request.getAttribute("activity")).address);
      out.write("\">\n");
      out.write("\t\t\t<input type=\"hidden\" name=\"transport\" id=\"accept-transport\" value=\"drive\">\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"acceptedid\" name=\"acceptedid\" value=\"");
      out.print(((Activity)request.getAttribute("activity")).id);
      out.write("\">\n");
      out.write("\t\t</form>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
